services:
  - type: web
    name: intelligent-document-query-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: API_HOST
        value: "0.0.0.0"
      - key: DEBUG
        value: "false"
      - key: CHUNK_SIZE
        value: "1000"
      - key: CHUNK_OVERLAP
        value: "200"
      - key: EMBEDDING_MODEL
        value: "all-MiniLM-L6-v2"
      - key: EMBEDDING_DIMENSION
        value: "384"
      - key: VECTOR_STORE_TYPE
        value: "faiss"
      - key: LLM_MODEL
        value: "gemini-2.0-flash-exp"
      - key: TOP_K_CHUNKS
        value: "15"
      - key: SIMILARITY_THRESHOLD
        value: "0.1"
      - key: MAX_FILE_SIZE
        value: "50000000"
      - key: REQUEST_TIMEOUT
        value: "300"
      - key: MAX_RETRIES
        value: "3"
      - key: GEMINI_API_KEY
        sync: false
